FROM nvidia/cuda:10.1-cudnn7-devel

RUN apt update -y; apt install -y \
    git \
    cmake \
    libsm6 \
    libxext6 \
    libxrender-dev \
    python3 \
    python3-pip \
    software-properties-common \
    gcc \
    g++ \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*

RUN pip3 install scikit-build

#Install dlib 
RUN cd ~ && \
    mkdir -p dlib && \
    git clone https://github.com/davisking/dlib.git dlib/ && \
    cmake -H/dlib -B/dlib/build -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1 && \
    cmake --build /dlib/build && \
    cd  dlib/ && \
    python3 /dlib/setup.py install && \
    cd ..

# Install the face recognition package
RUN mkdir /app && \
    cd /app
ADD requirements.txt .
RUN pip3 install -r requirements.txt
ADD main.py .
ADD model.py .
CMD ["python3", "main.py"]